apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "clamav.fullname" . }}-notify
subjects:
- kind: ServiceAccount
  name: {{ include "clamav.fullname" . }}-notify
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "clamav.fullname" . }}-notify
  apiGroup: rbac.authorization.k8s.io