apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-config
data:
  clamd.conf: |
    LogFile /dev/stdout
    LogTime yes
    LogClean yes
    LogSyslog no
    LogVerbose yes
    DatabaseDirectory /var/lib/clamav
    TCPSocket 3310
    Foreground yes
  freshclam.conf: |
    LogTime yes
    LogVerbose yes
    LogSyslog no
    DatabaseOwner clam
    DatabaseMirror http://{{ include "clamav.fullname" . }}-notify
    DatabaseMirror db.uk.clamav.net
    DatabaseMirror database.clamav.net
    Foreground yes
    NotifyClamd no