apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clamav.fullname" . }}
spec:
  podSelector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
    {{- if .Values.service.ingress }}
    from: {{ toYaml .Values.service.ingress | nindent 4 }}
    {{- end }}
