apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clamav.fullname" . }}-notify
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
