apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-notify-config
data:
  freshclam.conf: |
    Checks 24
    CompressLocalDatabase yes
    DatabaseOwner clam
    DatabaseMirror db.uk.clamav.net
    DatabaseMirror database.clamav.net
    TestDatabases yes
    OnUpdateExecute python /clam/notify.py clamav clamav
    LogVerbose yes
    NotifyClamd no