apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-notify-config
data:
  freshclam.conf: |
    Checks {{ .Values.clamavNotify.freshclam.checkFrequency }}
    CompressLocalDatabase yes
    DatabaseOwner clam
    {{- range .Values.clamavNotify.freshclam.mirrors }}
    DatabaseMirror {{ . }}
    {{- end }}
    TestDatabases yes
    OnUpdateExecute python /clam/notify.py {{ .Release.Namespace }} {{ include "clamav.fullname" . }}
    LogVerbose yes
    NotifyClamd no
