apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-notify
  ingress:
  - ports:
    - protocol: TCP
      port: 8080