apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "clamav.fullname" . }}-notify-cron
spec:
  schedule: "{{ .Values.clamavNotifyCron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "clamav.fullname" . }}-notify-cron
          containers:
          - name: clamav-notify-cron
            image: "{{ .Values.clamavNotifyCron.image }}:{{ default .Chart.AppVersion .Values.clamavNotifyCron.version }}"
            args: [
              "-n", "{{ .Release.Namespace }}",
              "-d", "{{ include "clamav.fullname" . }}",
              "-p", "{{ include "clamav.fullname" . }}-notify"
            ]
          restartPolicy: OnFailure