apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav.fullname" . }}-notify
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-notify
  template:
    metadata:
      labels:
        name: {{ include "clamav.fullname" . }}-notify
    spec:
      serviceAccountName: {{ include "clamav.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.clamavNotify.image }}:{{ .Values.clamavNotify.version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: clamav-notify-storage
            mountPath: /var/lib/clamav
          - name: config-volume
            mountPath: /etc/clamav
      volumes:
      - name: clamav-notify-storage
        persistentVolumeClaim:
          claimName: clamav-notify
      - name: config-volume
        configMap:
          name: clamav-notify-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "clamav.fullname" . }}-notify
  name: {{ include "clamav.fullname" . }}-notify
spec:
  ports:
  - name: {{ include "clamav.fullname" . }}-notify
    port: 80
    targetPort: 3310
  selector:
    name: {{ include "clamav.fullname" . }}-notify
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-notify
  ingress:
  - ports:
    - protocol: TCP
      port: 3310
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-notify
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-encrypted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi