apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav.fullname" . }}-notify
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-notify
  template:
    metadata:
      labels:
        name: {{ include "clamav.fullname" . }}-notify
    spec:
      serviceAccountName: {{ include "clamav.fullname" . }}-notify
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.clamavNotify.image }}:{{ default .Chart.AppVersion .Values.clamavNotify.version }}"
        imagePullPolicy: Always
        resources: {{ toYaml .Values.clamavNotify.resources | nindent 10 }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
        - name: LIGHTTPD_CONFIG
          value: /etc/config/lighttpd.conf
        volumeMounts:
        - name: clamav-notify-storage
          mountPath: /var/lib/clamav
        - name: config-volume
          mountPath: /etc/clamav/freshclam.conf
          subPath: freshclam.conf
        - name: config-volume
          mountPath: /etc/config/lighttpd.conf
          subPath: lighttpd.conf
      volumes:
      - name: clamav-notify-storage
        persistentVolumeClaim:
          claimName: clamav-notify
      - name: config-volume
        configMap:
          name: clamav-notify-config
