# Default values for clamav.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: clamav-notify

clamavNotify:
  image: quay.io/ukhomeofficedigital/acp-clamav-notify
  version: 0.0.2
