# Default values for clamav.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: clamav-notify

clamavHTTP:
  image: quay.io/ukhomeofficedigital/acp-clamav-http
  version: 0.0.6

clamavNotify:
  image: quay.io/ukhomeofficedigital/acp-clamav-notify
  version: 0.0.6
  volume:
    storageClass: gp2-encrypted
    size: 5

clamav:
  image: quay.io/ukhomeofficedigital/acp-clamav
  version: 0.0.6
  limits:
    fileSize: 20
    scanSize: 100
  resources:
    limits:
      cpu: 1500m
      memory: 3000M
  signaturesInMemory: false

nginxProxy:
  image: quay.io/ukhomeofficedigital/nginx-proxy
  version: v3.4.20