# Default values for clamav.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: clamav-notify

clamavHTTP:
  image: quay.io/ukhomeofficedigital/acp-clamav-http
  version: 0.0.4

clamavNotify:
  image: quay.io/ukhomeofficedigital/acp-clamav-notify
  version: 0.0.4

clamav:
  image: quay.io/ukhomeofficedigital/acp-clamav
  version: 0.0.4